name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Verify Java Version
        run: java -version

      - name: Build Project
        run: mvn clean compile

      - name: Run Tests
        run: mvn test

      - name: Package Application
        run: mvn package
      - name: Upload Project
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: target/*

     
